#' Generate Network
#'
#' Generate 3 kinds of networks for simulating. You can use
#' Random Network, Small World Network and Scale-Free Network.
#'
#' @param net_name String, the name of netwrok
#' @param net_params Vector, the params of generating network
#'
#' @return Network, List, store the name and graph generated by igraph
#' @export
#'
#' @examples generate_network("Random Network", c(10, "gnm", 100, "TRUE"))
#' generate_network("Random Network", 0.2)
generate_network = function(net_name, net_params) {
  # Random Network(ER)：使用Erdos-Renyi方法生成随机网络
  # 其生成方法有两个: G(n,p)和G(n,m)
  if (net_name == "Random Network") {
    # G(n, m)
    if (net_params[2] == "gnm") {
      net_graph <- igraph::erdos.renyi.game(net_params[1],
                                            net_params[3],
                                            type = "gnm",
                                            net_params[4])
    }
    # G(n, p)
    else{
      net_graph <- igraph::erdos.renyi.game(net_params[1],
                                            net_params[2])
    }
  }
  # Small World Network(WS)：使用Watts-Strogatz算法生成小世界网络
  # 其熵值在规则网络和随机网络之间。
  # 小世界效应：随着少数随机链路加入有结构的网络上，
  # 其平均路径长度会快速减少。
  else if (net_name == "Small World Network") {
    net_graph = igraph::watts.strogatz.game(1, net_params[1], net_params[2], net_params[3])
  }
  # Scale-free Network(BA)：使用Barabasi-Albert方法生成
  # 其度序列服从$h(k)=k^{-q}$的幂律分布
  # 简单说来，就是少量高度节点(hub)和大量低度节点
  else if (net_name == "Scale-free network") {
    net_graph = igraph::barabasi.game(net_param[1], power = net_params[2])
  }
  # 参数net_name错误
  else {
    cat("[Wrong]> Wrong network name!")
  }
  Network <- list(net_name, net_graph)
  names(Network) <- c("names", "graph")
  return(Network)
}
